#!/bin/bash

echo "Welcome!"

# Insert start range ip target 
echo "Insert first IP range target: "
read ip

# Insert end range ip target
echo "Insert last octect range target: "
read ott

# Insert port number target NB. !IF YOU WANT SCAN ALL PORTS SCANNER DIGIT 0!
echo "Insert port target (NB. IF YOU WANT SCAN ALL PORTS SCANNER DIGIT 0!) : "
read port

# Choose if you want use decoy IP
echo "Do you want to use decoy? (y/n): "
read use_decoy

# Initialization variable to accumulate decoy if you choose “y”
decoy_option=""

# If you choose “y” launch input to create decoy IP 
if [[ "$use_decoy" == "y" ]]; then
  echo "Insert decoy IP separated by commas and insert “ME” at the end of the list: "
  read decoy_ip
  decoy_option="-D $decoy_ip"
fi

# Launch nmap scanner against ip range & port selected and save results in file.txt in current directory
if [[ $port -eq 0 ]]; then
  nmap -Pn -sS -sU -p- $decoy_option "$ip-$ott" -T4 -vv --reason --open -oN result_scan_all.txt
else
  nmap -sS $decoy_option "$ip-$ott" -p "$port" -vv --reason --open -oN result_scan_"$port".txt
fi

# End scan
echo  "Scan exceuted!!"

# DISCLAIMER:
# This script is for educational and demonstration purposes only.
# It is intended to be used in controlled, legal environments such as labs or CTF challenges.
# Using nmap against systems you do not own or lack explicit authorization to test is illegal.
# The author is not responsible for any misuse or damage resulting from the execution of this script.
